### ISSUE TITLE
Post URLs are often wrong

### ISSUE THREAD

**Issue by kzar** [chander/social-network-cleaner#2]
I found that after the first ~200 posts were deleted every post URL was returning "Sorry, this page isn't available". The post URLs would look something like this:

`https://www.facebook.com/12345/posts/12345`

The first number is my user ID, the second the post ID. What I found was if I replaced my user ID with rge pretty version of my user ID the URL worked. So something like this:

`https://www.facebook.com/kzar/posts/12345`

The problem is I can't see any way to get the pretty user ID by using the Graph API. (Perhaps we should just prompt the user for it?)

(To get it working I just did something like this just before `self.delete_status(url)` call: `url = re.sub("12345", "kzar", url)`. It's a hack of course but it seems to be working fine and the purge of my posts continues!)

Cheers, Dave.

**Comment by kzar** [comment]
Just realised a better way than prompting the user, on the Facebook homepage the link at the top left to display the user's profile ends with the user's ID. Perhaps we could grab the ID from there using Selenium and then if the value isn't a number replace the user ID with it for post URLs?

**Comment by chander** [comment]
Right now when you start getting the error you've referenced, the cleaner pauses for awhile (if IIRC it's for about 2 hours) then continues.  The message itself seems to be some kind of throttling that Facebook applies to keep bulk operations from happening.  I've tried to add a bunch of throttles (already in place) in the code to minimize this effect.

I agree that changing to the username is a good idea, though I'm wondering if that happens for 200 more posts if that'll be throttled as well (thereby defeating the purpose of this change.)

However, I don't think that all users have usernames with facebook - that only happens if you choose a username, right?

I'm wondering if you've already got a local copy of the code that does this with your hard-coded username (and if so, if it starts returning the same error after ~200 posts or so?)

**Comment by kzar** [comment]
I don't think the two hour pause comes into effect because the page title contains "Page Not Found". I'm not exactly sure why using the "pretty" user ID instead of the numerical one in the URL works for me... but it does!

I've managed to delete hundreds more posts by running my hard-coded bodge so it does seem to improve things. I've just submitted a pull request that does it a little more properly, now it's using selenium to get the "pretty" user ID from the profile link on the home page. (As a bonus I've also set the Firefox window size as it was driving me crazy having to resize it every time I tested a change :p)

Cheers, Dave.
